version: 2
updates:

- package-ecosystem: gomod
  directory: /
  schedule:
    interval: weekly
  assignees:
  - fire833
  target-branch: main

- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily
  assignees:
  - fire833
  target-branch: main
  